export const agencyEndpoints = {
  addOpenIdSchema: (id: string) => `/openid4vc/issuer/${id}`,
  getOpenIdSchemas: `/openid4vc/issuer/supported-credentials`,
  offerOpenIdCredential: `/openid4vc/issuance-session/offer`,
  updateOpenIdCredentialState: (sessionId: string) =>
    `/openid4vc/issuance-session/${sessionId}`,
  requestOpenIdPresentation: `/openid4vc/verification-session/request`,
  updateOpenIdPresentationState: (sessionId: string) =>
    `/openid4vc/verification-session/${sessionId}`,
  createAnoncredsSchema: `/schemas`,
  getAnoncredsSchemas: `/schemas`,
  createSchema: `/v2/schemas`,
  updateSchema: (schemaId: string) => `/v2/schemas/${schemaId}`,
  getSchemaList: `/v2/schemas`,
  registerSchema: (id: string) => `/v2/schemas/${id}/registration`,
  getSingleSchema: (id: string) => `/v2/schemas/${id}`,
  getSchemaRegistration: (id: string) => `/v2/schemas/${id}/registration`,
  getTemplateList: `/issuance-templates`,
  createAnoncredsCredentialDefinition: `/credential-definitions`,
  getAnoncredsCredentialDefinition: `/credential-definitions`,
  createAnoncredsRevocationRegistry: `/revocation-registries`,
  createDid: `/dids`,
  getDids: `/dids`,
  getDidMethods: `/dids/methods`,
  createOpenIdIssuer: `/openid4vc/issuer`,
  createOpenIdVerifier: `/openid4vc/verifier`,
  createConnection: 'connections/create-invitation',
  getConnectionState: (id: string) => `connections/${id}`,
  offerAnoncredsCredential: `/credentials/offer`,
  getCredentialConfig: '/credentials/config',
  getAnoncredsCredentialState: (id: string) => `credentials/${id}`,
  requestAnoncredsPresentation: `/proofs/request`,
  getAnoncredsPresentationState: (id: string) => `proofs/${id}`,
  getUserData: `/user`,
  patchUserData: `/user`,
  createIssuanceTemplate: `/issuance-templates`,
  updateIssuanceTemplate: (id: string) => `/issuance-templates/${id}`,
  deleteIssuanceTemplate: (id: string) => `/issuance-templates/${id}`,
  getIssuanceTemplateList: `/issuance-templates`,
  getSingleIssuanceTemplate: (id: string) => `/issuance-templates/${id}`,
  createVerificationTemplate: `/verification-templates`,
  updateVerificationTemplate: (id: string) => `/verification-templates/${id}`,
  deleteVerificationTemplate: (id: string) => `/verification-templates/${id}`,
  getVerificationTemplateList: `/verification-templates`,
  getSingleVerificationTemplate: (id: string) =>
    `/verification-templates/${id}`,
  prepareWallet: '/prepare-wallet',
};
