name: Build and release Android APK & AAB for Heka Wallet

on:
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    defaults:
      run:
        working-directory: ./heka-wallet
    name: Build Android APK & AAB
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Prepare Github Runner
        uses: pandaswhocode/initialize-github-job@0ed960ecaed898893e404ad55c7aa12fdc3b2a53 # v1.4.0
        with:
          checkout: 'true'
          checkout-ref: '${{ github.ref }}'
          checkout-token: '${{ secrets.GITHUB_TOKEN }}'
          checkout-fetch-depth: '0'
          setup-java: 'true'
          java-version: '17'
          java-distribution: 'zulu'
          java-cache: 'gradle'
          setup-node: 'true'
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - name: Install dependencies
        run: yarn install --immutable
        shell: bash

      - name: Get app version
        id: version
        working-directory: ./heka-wallet/app
        run: echo "version=$(nbgv get-version -v NpmPackageVersion)" >> $GITHUB_OUTPUT

      - name: Bundle Heka Wallet debug
        run: yarn bundle-app:android:debug
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Prepare artifacts
        id: prepare_artifacts
        run: |
          mkdir "output"
          cp "app/android/app/build/outputs/apk/debug/app-debug.apk" "output/heka-wallet.apk"

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build artifacts
          path: heka-wallet/output/


